name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test --runInBand

      - name: Run E2E Tests
        run: |
          if [ -z "$(find tests/e2e -name '*.spec.ts')" ]; then
            echo "No E2E tests found. Skipping."
          else
            yarn test:e2e
          fi
